
var CONFIG = CONFIG || {};

CONFIG.KING_Y = 100;
CONFIG.SOUND_ON = false;
CONFIG.GAME_TIME = 3;

CONFIG.CHECK_WECHAT = false;

CONFIG.FLYER_INTERVAL = 0.4;
CONFIG.BOMB_INTERVAL = 3;
CONFIG.TIME_INTERVAL = 5;


CONFIG.CONTAINER = {
		FLYER:[],
		SCROLL_LABEL:[]
};

CONFIG.OPENID = "";
CONFIG.AVATAR = "";
CONFIG.NICKNAME = "游客";
CONFIG.MAGICKEY = "GFGJHDQWRQRWYHJKFGJDFSGDFSERWR";

CONFIG.SERVER_URL = "http://127.0.0.1:8080/";
CONFIG.SERVER_ACTION_SCORE = "game/score";