var AwardType = [
                 {
                	 res:res.A0,
                	 level:1
                 },
                 {
                	 res:res.A1,
                	 level:2
                 },
                 {
                	 res:res.A2,
                	 level:3
                 },
                 {
                	 res:res.A3,
                	 level:4
                 },
                 {
                	 res:res.A4,
                	 level:5
                 },
                 ];