var AwardType = [
                 {
                	 res:res.F0,
                	 level:1
                 },
                 {
                	 res:res.F1,
                	 level:2
                 },
                 {
                	 res:res.F2,
                	 level:3
                 },
                 {
                	 res:res.F3,
                	 level:4
                 },
                 {
                	 res:res.F4,
                	 level:5
                 },
                 ];