var FlyerType = [
                 {
                	 type:0,
                	 textureName:res.F0,
                	 scoreValue:30,
                	 speed:7
                 },
                 {
                	 type:1,
                	 textureName:res.F1,
                	 scoreValue:60,
                	 speed:7
                 },
                 {
                	 type:2,
                	 textureName:res.F2,
                	 scoreValue:100,
                	 speed:6
                 },
                 {
                	 type:3,
                	 textureName:res.F3,
                	 scoreValue:150,
                	 speed:6
                 },
                 {
                	 type:4,
                	 textureName:res.F4,
                	 scoreValue:200,
                	 speed:5
                 },
                 {
                	 type:5,
                	 textureName:res.F5,
                	 scoreValue:250,
                	 speed:4
                 },
                 {
                	 type:6,
                	 textureName:res.F6,
                	 scoreValue:300,
                	 speed:3
                 },
                 {
                	 type:7,// 时间
                	 textureName:res.F7,
                	 scoreValue:3,
                	 speed:3
                 },
                 {
                	 type:8,// 时间
                	 textureName:res.F8,
                	 scoreValue:5,
                	 speed:3
                 },
                 {
                	 type:9,// 炸弹
                	 textureName:res.F9,
                	 scoreValue:5,
                	 speed:3
                 },
                 ];