var res = {
	m_bomb : "res/music/bomb.mp3",
	m_collide : "res/music/collide.mp3",
	m_time : "res/music/time.mp3",
	//m_loop : "res/music/loop.mp3",
	
	//启动
	bg_launch : "res/imgs/bg_loading_s.png",
	btn_start : "res/imgs/btn_start.png",
	// 游戏
	bg_game : "res/imgs/bg_game_s.jpg",
	bg_bomb : "res/imgs/bg_bomb.jpg",
	img_king : "res/imgs/king.png",
	img_king_black : "res/imgs/king_black.png",
	F0 : "res/imgs/F0.png",
	F1 : "res/imgs/F1.png",
	F2 : "res/imgs/F2.png",
	F3 : "res/imgs/F3.png",
	F4 : "res/imgs/F4.png",
	F5 : "res/imgs/F5.png",
	F6 : "res/imgs/F6.png",
	F7 : "res/imgs/F7.png",
	F8 : "res/imgs/F8.png",
	F9 : "res/imgs/F9.png",
	F10 : "res/imgs/F10.png",
	
	
	//result
	bg : "res/imgs/bg.jpg",
    btn_again : "res/imgs/btn_again.png",
    btn_share : "res/imgs/btn_share.png",
    btn_award : "res/imgs/btn_award.png",
    btn_no : "res/imgs/btn_no.png",
    btn_yes : "res/imgs/btn_yes.png",
    btn_help : "res/imgs/btn_help.png",
    img_arrow : "res/imgs/arrow.png",
    guest_tips : "res/imgs/guest_tips.png",
    fans_tips : "res/imgs/fans_tips.png",
    award_pocket : "res/imgs/award_pocket.png",
    award_pocket_fans : "res/imgs/award_pocket_fans.png",
    btn_shenming : "res/imgs/btn_shenming.png",
    award_6:"res/imgs/award_6.png",
    A0 : "res/imgs/a_0.png",
    A1 : "res/imgs/a_1.png",
    A2 : "res/imgs/a_2.png",
    A3 : "res/imgs/a_3.png",
    A4 : "res/imgs/a_4.png",
    A5 : "res/imgs/a_5.png",
    NO1 : "res/imgs/NO1.png",
    NO2 : "res/imgs/NO2.png",
    NO3 : "res/imgs/NO3.png",
    NO : "res/imgs/NO.png",
    bg_result : "res/imgs/bg_result.jpg",
    result_title : "res/imgs/result_title.png",
    result_header : "res/imgs/result_header.png",
    result_line : "res/imgs/result_line.png",
    default_avatar : "res/imgs/default_avatar.png",
    share_1 : "res/imgs/share_1.png",
    award_guest : "res/imgs/award_guest.jpg",
    award_fans : "res/imgs/award_fans.jpg",
    guest_award_tips:"res/imgs/guest_award_tips.png",
    guest_award_tips_2:"res/imgs/guest_award_tips_2.png",
    LV1:"res/imgs/LV1.png",
    LV2:"res/imgs/LV2.png",
    LV3:"res/imgs/LV3.png",
    LV4:"res/imgs/LV4.png",
    LV5:"res/imgs/LV5.png",
    LV6:"res/imgs/LV6.png",
    award_package_6:"res/imgs/award_package_6.png"
   
};

var g_resources = [];

var g_res_game = [
res.bg_launch,
res.btn_start,
res.bg_bomb,
res.img_king,
res.img_king_black,
res.F0,
res.F1,
res.F2,
res.F3,
res.F4,
res.F5,
res.F6,
res.F7,
res.F8,
res.F9,
res.F10
                   ];
var g_res_result = [
res.btn_again,
res.btn_share,
res.btn_award,
res.btn_no,
res.btn_yes,
res.btn_help,
res.img_arrow,
res.A0,
res.A1,
res.A2,
res.A3,
res.A4,
res.A5,
res.bg_result,
res.result_title,
res.result_header,
res.result_line,
res.default_avatar,
res.share_1,
res.award_guest,
res.award_fans,
res.guest_tips,
res.award_pocket_fans,
res.fans_tips,
//res.bg,
res.award_6,
res.btn_shenming,
res.NO,
res.NO1,
res.NO2,
res.NO3,
res.LV1,
res.LV2,
res.LV3,
res.LV4,
res.LV5,
res.LV6,
res.guest_award_tips,
res.guest_award_tips_2,
res.award_package_6
	];

/*for (var i in res) {
    g_resources.push(res[i]);
}*/
